language: node_js
node_js:
  - "lts/*"
cache:
   directories:
      - ~/.npm
      - ~/.cache
stages:
  - tests
  - name: master
    if: branch = master
  - name: tag
    if: tag IS present

jobs:
  include:
    - stage: tests
      script: npm run cypress_tests

    - stage: tests
      addons:
        chrome: stable
      name: Axe_tests
      script:
        - npm run axe_tests